<?php
/**
 * Implements hook_init()
 */
function menu_active_trail_init() {
  //$menus = menu_get_active_trail();
  //dpm($menus);
  //dpm(menu_tree('main-menu'));
  //dpm(menu_get_active_trail());
  //dpm(menu_get_item());
  //dpm(menu_main_menu());
  //$trail = menu_get_active_trail();
  //$trail[1];
  //dpm($trail[1]);
  //dpm(drupal_attributes($trail[2]));
  //$path = $_GET['q'];
  //dpm($path);
  //$menu_items = menu_tree('main-menu');
  /*
  foreach($menu_items as $num => $item) {
  	if(strstr($num, 'active-trail')) {
	  $item['attributes']['class'][] = 'active';
      dpm($item);
	  return;
	}
  }
  */
  //$menu_items[837]['#attributes']['class'][] = 'active';
  //dpm($menu_items);
}

/*
function menu_active_trail_menu_block_tree_alter(&$tree, &$config) {
  //dpm($tree['50000 Batman main 837']);
  //$tree['50000 Batman main 837']['link']['options']['class'] = 'active';

  dpm($tree);
}
*/

/**
 * Implements hook_preprocess_menu_link().
function menu_active_trail_preprocess_menu_link(&$items) {
  dpm($items);
}
 */

/**
 * Implements hook_menu_alter().
 */
function menu_active_trail_menu_alter(&$link) {
  dpm($link);
}
